export default [
    //   {
    //     title: "敬拜",
    //     location: "莘塍",
  
    //     teacher: "园长",
    //     week: 2,
    //     start: 1,
    //     duration: 1,
    //     weeks: Array.from({ length: 20 }, (_, index) => index + 1),
    //   },
    //   {
    //     title: "敬拜",
    //     location: "莘塍",
    //     teacher: "园长",
    //     week: 3,
    //     start: 1,
    //     duration: 1,
    //     weeks: Array.from({ length: 20 }, (_, index) => index + 1),
    //   },
    //   {
    //     title: "敬拜",
    //     location: "莘塍",
    //     teacher: "园长",
    //     week: 5,
    //     start: 1,
    //     duration: 1,
    //     weeks: Array.from({ length: 20 }, (_, index) => index + 1),
    //   },
    //   {
    //     title: "敬拜",
    //     location: "莘塍",
    //     teacher: "园长",
    //     week: 6,
    //     start: 1,
    //     duration: 1,
    //     weeks: Array.from({ length: 20 }, (_, index) => index + 1),
    //   },
    {
      title: "橄榄球",
      location: "阁巷",
      teacher: "Joseph",
      week: 4,
      start: 1,
      duration: 3,
      weeks: Array.from({ length: 20 }, (_, index) => index + 1),
    },
  
    {
      title: "英文",
      location: "莘塍",
      teacher: "Wendy",
      week: 2,
      start: 4,
      duration: 1,
      weeks: Array.from({ length: 20 }, (_, index) => index + 1),
    },
    {
      title: "英文",
      location: "莘塍",
  
      teacher: "Wendy",
      week: 5,
      start: 4,
      duration: 1,
      weeks: Array.from({ length: 20 }, (_, index) => index + 1),
    },
  
    {
      title: "画画",
      location: "九里",
      teacher: "David",
      week: 3,
      start: 4,
      duration: 2,
      weeks: Array.from({ length: 20 }, (_, index) => index + 1),
    },
    {
      title: "户外课",
      location: "明镜",
      teacher: "家长",
      week: 6,
      start: 4,
      duration: 2,
      weeks: Array.from({ length: 20 }, (_, index) => index + 1),
    },
  ];
  